# the location of the ti software directory
ifeq ($(OS),Windows_NT)
   TI-SOFTWARE       := C:/ti-software
else
   TI-SOFTWARE       := $(HOME)/Taguino/
endif   

# include hwlib
HWLIB             ?= $(TI-SOFTWARE)/hwlib
include           $(HWLIB)/makefile.inc

# set BMPTK to the bmptk subdirectory
BMPTK             ?= $(TI-SOFTWARE)/bmptk

# Defer to the bmptk/Makefile.inc to do the work
include $(BMPTK)/Makefile.inc
