SOURCES := entities.cpp input.cpp button.cpp KY040.cpp HCSR04.cpp game.cpp scoreboard.cpp RGBLed.cpp
SOURCES += display.cpp NRF24.cpp signup.cpp interface.cpp keypad.cpp mp3.cpp

HEADERS := entities.hpp input.hpp button.hpp KY040.hpp HCSR04.hpp game.hpp scoreboard.hpp RGBLed.hpp
HEADERS += display.hpp applicationLogic.hpp NRF24.hpp NRF24_register.hpp signup.hpp interface.hpp keypad.hpp mp3.hpp

SEARCH  := Boundary/Infrared Boundary/HCSR04 Boundary/KY040 Entity Boundary Control Boundary/Infrared Boundary/Display Boundary/buttoninterrupt 
SEARCH  += Boundary/RGBLed ApplicationLogic Boundary/NRF Boundary/keypadtask Boundary/Mp3 

RELATIVE := ..
include $(RELATIVE)/Makefile.due
